import Head from 'next/head';

import Layout from '@/components/layout/Layout';
import { APP_TITLE } from '@/constants/config';
import UserManagementDetail from '@/views/UserManagement/UserManagementDetail';

const UserManagementDetailPage = () => (
  <>
    <Head>
      <title>{`${APP_TITLE} - User Access Management` }</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <UserManagementDetail />
    </Layout>
  </>
);

export default UserManagementDetailPage;
