import Head from 'next/head';

import Layout from '@/components/layout/Layout';
import { APP_TITLE } from '@/constants/config';
import List from '@/views/List';

const Dashboard = () => (
  <>
    <Head>
      <title>{APP_TITLE}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <List />
    </Layout>
  </>
);

export default Dashboard;
