import { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

import Layout from '@/components/layout/Layout';
import { APP_TITLE } from '@/constants/config';
import { useAuthContext } from '@/contexts/AuthContext';
import useToaster from '@/hooks/useToaster';
import Dashboard from '@/views/Dashboard';

const DashboardPage = () => {
  const { isAuthenticated, profile } = useAuthContext();
  const router = useRouter();
  const toaster = useToaster();
  useEffect(() => {
    if (!isAuthenticated || !profile) {
      toaster.show('You need to login');
      router.push('/login');
    }
  }, [isAuthenticated, profile, router, toaster]);
  return (
    <>
      <Head>
        <title>{`${APP_TITLE} - Dashboard`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Dashboard />
      </Layout>
    </>
  );
};

export default DashboardPage;
