import Head from 'next/head';

import List from 'src/views/List';

import Layout from '@/components/layout/Layout';

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <List />
    </Layout>
  </>
);

export default Home;
