import Head from 'next/head';

import Layout from '@/components/layout/Layout';
import PokemonList from '@/features/PokemonList';

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    </Head>
    <Layout>
      <PokemonList />
    </Layout>
  </>
);

export default Home;
